<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>sdbc</string>
   </array>
  <key>name</key>
  <string>sdbc</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.sdbc</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(NAME)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.sdbc</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#uid_NAME</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^(?=.{0,1})(?:|))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.sdbc</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(VERSION)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.sdbc</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#uid_VERSION</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^(?=.{0,1})(?:|))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.sdbc</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(CONF)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.sdbc</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#uid_CONF</string>
            </dict>
           </array>
          <key>end</key>
          <string>((?=(NODE|FORMAT|TYPE|VERSION|NAME|CONF)([^\w])))</string>
          <key>endCaptures</key>
          <dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(NODE)([^\w])</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.sdbc</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#uid_NODE</string>
            </dict>
           </array>
          <key>end</key>
          <string>((?=(NODE|FORMAT|TYPE|VERSION|NAME|CONF)([^\w])))</string>
          <key>endCaptures</key>
          <dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(FORMAT)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.sdbc</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#uid_FORMAT</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^(?=.{0,1})(?:|))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.sdbc</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(TYPE)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.sdbc</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#uid_TYPE</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^(?=.{0,1})(?:|))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.sdbc</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#illegal</string>
        </dict>
       </array>
    </dict>
    <key>ADODI</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(ANALOG|DIGITAL)</string>
          <key>name</key>
          <string>keyword.sdbc</string>
        </dict>
       </array>
    </dict>
    <key>ID</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>([A-Z_]+[A-Z0-9_]*)</string>
          <key>name</key>
          <string>variable.sdbc</string>
        </dict>
       </array>
    </dict>
    <key>INTFLO</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(INTEGER|FLOATING)</string>
          <key>name</key>
          <string>keyword.sdbc</string>
        </dict>
       </array>
    </dict>
    <key>IO</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(OUTPUT|INPUT)</string>
          <key>name</key>
          <string>keyword.sdbc</string>
        </dict>
       </array>
    </dict>
    <key>comment</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\s#.*)</string>
          <key>name</key>
          <string>comment.sdbc</string>
        </dict>
       </array>
    </dict>
    <key>desc_0</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(\s+(?&lt;=(.*:.*){0}):)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.documentation.sdbc</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#uid_description</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^(?=.{0,1})(?:|))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.sdbc</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>desc_1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(\s+(?&lt;=(.*:.*){1}):)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.documentation.sdbc</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#uid_description</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^(?=.{0,1})(?:|))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.sdbc</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>flow</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\s)(&lt;&lt;|&gt;&gt;)(\s)</string>
          <key>name</key>
          <string>keyword.control.sdbc</string>
        </dict>
       </array>
    </dict>
    <key>illegal</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>([^\s])</string>
          <key>name</key>
          <string>invalid.sdbc</string>
        </dict>
       </array>
    </dict>
    <key>main__14</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(,)</string>
          <key>name</key>
          <string>punctuation.sdbc</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#number</string>
        </dict>
       </array>
    </dict>
    <key>main__15</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(,)</string>
          <key>name</key>
          <string>punctuation.sdbc</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#number</string>
        </dict>
       </array>
    </dict>
    <key>main__4</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#seperator</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#illegal</string>
        </dict>
       </array>
    </dict>
    <key>number</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>([\x{002b}-]?([0-9]+|[0-9]+\.[0-9]+))</string>
          <key>name</key>
          <string>constant.numeric.sdbc</string>
        </dict>
       </array>
    </dict>
    <key>numeric</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(0x[A-Fa-f0-9]+|[0-9]+)</string>
          <key>name</key>
          <string>constant.numeric.sdbc</string>
        </dict>
       </array>
    </dict>
    <key>seperator</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\s+:\s+)</string>
          <key>name</key>
          <string>punctuation.sdbc</string>
        </dict>
       </array>
    </dict>
    <key>string</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(\&quot;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>text.sdbc</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#uid_string</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\&quot;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>text.sdbc</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>uid_ADDR</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\s+-\s+)</string>
          <key>name</key>
          <string>punctuation.sdbc</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#desc_0</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#illegal</string>
        </dict>
       </array>
    </dict>
    <key>uid_CONF</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(ANALOG_RES|VIRT_ID_OFF)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.sdbc</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__4</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^(?=.{0,1})(?:|))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.sdbc</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#illegal</string>
        </dict>
       </array>
    </dict>
    <key>uid_FORMAT</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#string</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#desc_0</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.sdbc</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__14</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.sdbc</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\[)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.sdbc</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__15</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\])</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.sdbc</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#illegal</string>
        </dict>
       </array>
    </dict>
    <key>uid_GPIO</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#ADODI</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#IO</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#ID</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#desc_1</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#seperator</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#illegal</string>
        </dict>
       </array>
    </dict>
    <key>uid_LINK</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(SET)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.sdbc</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#uid_SET</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^(?=.{0,1})(?:|))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.sdbc</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#flow</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#ID</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#desc_0</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#illegal</string>
        </dict>
       </array>
    </dict>
    <key>uid_MSG</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(SIG)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.sdbc</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#uid_SIG</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^(?=.{0,1})(?:|))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.sdbc</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#flow</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#ID</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#desc_0</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#seperator</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#illegal</string>
        </dict>
       </array>
    </dict>
    <key>uid_NAME</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#string</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#illegal</string>
        </dict>
       </array>
    </dict>
    <key>uid_NODE</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(GPIO)([^\w])</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.sdbc</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#uid_GPIO</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^(?=.{0,1})(?:|))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.sdbc</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(VIRT)([^\w])</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.sdbc</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#uid_VIRT</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^(?=.{0,1})(?:|))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.sdbc</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(ADDR)([^\w])</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.sdbc</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#uid_ADDR</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^(?=.{0,1})(?:|))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.sdbc</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(MSG)([^\w])</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.sdbc</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#uid_MSG</string>
            </dict>
           </array>
          <key>end</key>
          <string>((?=(NODE|MSG|GPIO|VIRT|LINK|ADDR|FORMAT|TYPE|SET|VERSION|NAME|CONF)([^\w])))</string>
          <key>endCaptures</key>
          <dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(LINK)(?=\s)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.sdbc</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#uid_LINK</string>
            </dict>
           </array>
          <key>end</key>
          <string>((?=(NODE|MSG|GPIO|VIRT|LINK|ADDR|FORMAT|TYPE|SIG|VERSION|NAME|CONF)([^\w])))</string>
          <key>endCaptures</key>
          <dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#ID</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#desc_0</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#illegal</string>
        </dict>
       </array>
    </dict>
    <key>uid_SET</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#ID</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#flow</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#desc_0</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#illegal</string>
        </dict>
       </array>
    </dict>
    <key>uid_SIG</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#ID</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#desc_1</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#seperator</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#string</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#flow</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#illegal</string>
        </dict>
       </array>
    </dict>
    <key>uid_TYPE</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#INTFLO</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#string</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\+|-)</string>
          <key>name</key>
          <string>punctuation.sdbc</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#desc_0</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#illegal</string>
        </dict>
       </array>
    </dict>
    <key>uid_VERSION</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\b\d+\.\d+\.\d+)</string>
          <key>name</key>
          <string>constant.numeric.sdbc</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#illegal</string>
        </dict>
       </array>
    </dict>
    <key>uid_VIRT</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#ADODI</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#IO</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#ID</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#desc_1</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#seperator</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#illegal</string>
        </dict>
       </array>
    </dict>
    <key>uid_description</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(.*)</string>
          <key>name</key>
          <string>comment.documentation.sdbc</string>
        </dict>
       </array>
    </dict>
    <key>uid_string</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>([^\x{0022}\x{005c}]*(\\.[^\x{0022}\x{005c}]*)*)</string>
          <key>name</key>
          <string>text.sdbc</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
